In [2]:
import numpy as np
print (np)
print (np.__version__)

<module 'numpy' from 'c:\\Users\\COM0021\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
1.21.5


In [6]:
a = np.arange(15).reshape(3,5)
print(a)
# array([[ 0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14]])

print(type(a)) # <type 'numpy.ndarray'>

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>
