# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [3]:
np.zeros可以產生一個完全為0的陣列
np.empty會產生一個近似於0的陣列

'\nYour Code\n'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [5]:
# 參考解答

a = np.random.rand(2, 3)
a=a*100
print(a)
print(a.round())
print(np.array(a,dtype=int))

[[53.9266722   7.11500009 27.97776518]
 [48.54405822 85.79151974 41.73537774]]
[[53  7 27]
 [48 85 41]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [6]:
m = 20
n = 40
a = np.random.rand(2, 3)*(n-m)
b=a
print(a)


[[ 5.73549803 10.15765022  5.91257444]
 [ 9.91126182 11.30802698 11.33204089]]


In [7]:
print(b%1)

[[0.73549803 0.15765022 0.91257444]
 [0.91126182 0.30802698 0.33204089]]


In [8]:
print(a-b%1+m)

[[25. 30. 25.]
 [29. 31. 31.]]
