# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [1]:
# 記得先 Import 正確的套件

import numpy as np 

In [2]:
E = np.arange(11)
E[(E >= 3) & (E < 7)] *= -1
print(E)

[ 0  1  2 -3 -4 -5 -6  7  8  9 10]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [5]:
A = np.random.rand(3, 6)

print(A[A>0.5])
print(A[A>0.5].size)

[0.97880228 0.65497234 0.72507242 0.87573141 0.97123234]
5


In [8]:
import numpy as np 

np.searchsorted(
    [1, 2, 3, 4, 5,6],
    [-10, 10,11, 3, 5]
)

array([0, 6, 6, 2, 4], dtype=int64)